export default abstract class Constants {

    public static WORKSPACE_CONFIG = 'navigator';

    public static COMMANDS = {
        SEARCH: "SEARCH",
        REVERSE_SEARCH: "REVERSE SEARCH",
        PATTERN_SEARCH: "PATTERN SEARCH",
        REVERSE_PATTERN_SEARCH: "REVERSE PATTERN SEARCH",
        JUMP_LINES: "JUMP LINES",
        JUMP_TO_LINE_LAST_CHAR_OCCURRENCE: "LINE LAST CHAR OCCURRENCE",
        JUMP_TO_LINE_FIRST_CHAR_OCCURRENCE: "LINE FIRST CHAR OCCURRENCE",
        JUMP_TO_LINE_N_CHAR: "LINE N CHAR",
        JUMP_TO_NEXT_CURSOR_MATCH: "CURSOR MATCH",
        JUMP_TO_REVERSE_CURSOR_MATCH: "REVERSE CURSOR MATCH",
        JUMP_TO_NEXT_PARAGRAPH: 'NEXT PARAGRAPH',
        JUMP_TO_PREVIOUS_PARAGRAPH: 'PREVIOUS PARAGRAPH',
        JUMP_TO_NEXT_SYMBOL: 'NEXT SYMBOL',
        JUMP_TO_PREVIOUS_SYMBOL: 'PREVIOUS SYMBOL'
    }

    public static FEEDBACK_STYLE = {
        NONE: 'none',
        STATUS_BAR: 'statusbar',
        NOTIFICATION: 'notification'
    }

}